sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t 8f89f8ca62c2 -f Dockerfile.dev .

script:
    - docker run -e CI=true 8f89f8ca62c2 npm run test -- --coverage

after_success:
    - echo "Test Success"